services:
  gatebot:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: aql_gatebot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
